### ISSUE TITLE
Google Parsing error

### ISSUE THREAD

**Issue by mangaflux01** [viruzx/Sitemap-Generator-Crawler#25] opened 2017-08-29 15:56 UTC
i got this error when i submitted the map to google 

Errors | Parsing error | We were unable to read your Sitemap. It may contain an entry we are unable to recognize. Please validate your Sitemap before resubmitting.
-- | -- | --

please tell me how to fix i dont have computer back ground

**Comment by vezaynk** [comment] 2017-08-29 16:08
Please give me your sitemap and your url you are scanning

**Comment by mangaflux01** [comment] 2017-08-29 16:12
URL is http://mangaflux.com
http://mangaflux.com/sitemap.xml
link to ur script is http://mangaflux.com/sitemap.php

**Comment by mangaflux01** [comment] 2017-08-29 16:17
this is the PHP FIle with the changes i did

```
//Site to crawl
$site = "https://mangaflux.com" . "/";

//Location to save file
$file = "sitemap.xml";

//How many layers of recursion are you on, my dude?
$max_depth = 0;

//These two are relative. It's pointless to enable them unless if you intend to modify the sitemap later.
$enable_frequency = false;
$enable_priority = false;

//Tells search engines the last time the page was modified according to your software
//Unreliable: disabled by default
$enable_modified = false;

//Some sites have misconfigured but tolerable SSL. Disable this for those cases.
$curl_validate_certificate = true;

//Relative stuff, ignore it
$freq = "daily";
$priority = "1";

//The pages will not be crawled and will not be included in sitemap
//Use this list to exlude non-html files to increase performance and save bandwidth
$blacklist = array(
    "*.jpg",
    "*/secrets/*",
    "https://www.mangaflux.com/a"
);


/* NO NEED TO EDIT BELOW THIS LINE */

$debug = array(
    "add" => true,
    "reject" => true,
    "warn" => true
);

[KNYZORG REMOVED ALL NON-CONFIG RELATED CODE]
```

**Comment by vezaynk** [comment] 2017-08-29 18:29
This is the most horribly-styled issue that I got in my life. Checking it out anyways.

Issue seems to be that the last part of the sitemap was not written. I suspect that the script timed out but am not sure.

**Comment by mangaflux01** [comment] 2017-08-29 18:38
sorry for that i tried to format it but to no avail and thank you for taking interest

**Comment by vezaynk** [comment] 2017-08-29 21:30
It would appear, that the script takes a really long time to parse your site beyond some point.

I ran it on my phone and it took slightly over 2 and a half hours.

So you are dealing with a performance issue and not a bug per-say.

I am at a bus stop right now. Will give you more stuff when I'm home.

**Comment by vezaynk** [comment] 2017-08-29 23:05
This is what the eventual output looks like to me: https://goo.gl/photos/KKp68pdrfqxTPmPb9

The issue is broken into 2 issues:

 - overwriting before completion
 - performance improvements

I have done what I can so far with the latter. The former will get a new issue.

**Comment by vezaynk** [comment] 2017-08-29 23:14
I am closing this issue. Feel free to track progress on both fronts in issues #26 and #27

**Closed as completed** 2017-08-29 23:14 UTC
Labels: bug/missing feature
